config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  resources :twitter_users
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :tweet
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord


belongs_to :twitter_users



end

app/models/twitter_service.rb
require 'twitter'
class TwitterService < ApplicationRecord

  class << self

    def get_data(hashtag)
      puts "Secret is " + Rails.application.secrets.twitter_apikey
      @client = Twitter::REST::Client.new do |config|
        config.consumer_key       =  Rails.application.secrets.twitter_apikey
        config.consumer_secret    =  Rails.application.secrets.twitter_apisecret
        config.access_token        = Rails.application.secrets.twitter_oauthtoken
        config.access_token_secret = Rails.application.secrets.twitter_oauthsecret

      end
      search(hashtag)
    end

    def search(string)
      objects =  @client.search(string,result_type: "popular", lang: 'en').take(20)
      objects.each do |status|

      end
    end

  end


end

app/models/twitter_user.rb
class TwitterUser < ApplicationRecord

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:show, :edit, :update, :destroy]

  # GET /hashtags
  # GET /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1
  # GET /hashtags/1.json
  def show
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags
  # POST /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully created.' }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1
  # PATCH/PUT /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully updated.' }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1
  # DELETE /hashtags/1.json
  def destroy
    @hashtag.destroy
    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: 'Hashtag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hashtag_params
      params.fetch(:hashtag, {})
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:sentiment)
    end
end

app/controllers/twitter_users_controller.rb
class TwitterUsersController < ApplicationController
  before_action :set_twitter_user, only: [:show, :edit, :update, :destroy]

  # GET /twitter_users
  # GET /twitter_users.json
  def index
    @twitter_users = TwitterUser.all
  end

  # GET /twitter_users/1
  # GET /twitter_users/1.json
  def show
  end

  # GET /twitter_users/new
  def new
    @twitter_user = TwitterUser.new
  end

  # GET /twitter_users/1/edit
  def edit
  end

  # POST /twitter_users
  # POST /twitter_users.json
  def create
    @twitter_user = TwitterUser.new(twitter_user_params)

    respond_to do |format|
      if @twitter_user.save
        format.html { redirect_to @twitter_user, notice: 'Twitter user was successfully created.' }
        format.json { render :show, status: :created, location: @twitter_user }
      else
        format.html { render :new }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitter_users/1
  # PATCH/PUT /twitter_users/1.json
  def update
    respond_to do |format|
      if @twitter_user.update(twitter_user_params)
        format.html { redirect_to @twitter_user, notice: 'Twitter user was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter_user }
      else
        format.html { render :edit }
        format.json { render json: @twitter_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_users/1
  # DELETE /twitter_users/1.json
  def destroy
    @twitter_user.destroy
    respond_to do |format|
      format.html { redirect_to twitter_users_url, notice: 'Twitter user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter_user
      @twitter_user = TwitterUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_user_params
      params.require(:twitter_user).permit(:username, :twittter_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/twitter_users_helper.rb
module TwitterUsersHelper
end

app/views/hashtags/_form.html.erb
<%= form_for(hashtag) do |f| %>
  <% if hashtag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
      <% hashtag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hashtags/edit.html.erb
<h1>Editing Hashtag</h1>

<%= render 'form', hashtag: @hashtag %>

<%= link_to 'Show', @hashtag %> |
<%= link_to 'Back', hashtags_path %>

app/views/hashtags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hashtags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hashtags.each do |hashtag| %>
      <tr>
        <td><%= link_to 'Show', hashtag %></td>
        <td><%= link_to 'Edit', edit_hashtag_path(hashtag) %></td>
        <td><%= link_to 'Destroy', hashtag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hashtag', new_hashtag_path %>

app/views/hashtags/new.html.erb
<h1>New Hashtag</h1>

<%= render 'form', hashtag: @hashtag %>

<%= link_to 'Back', hashtags_path %>

app/views/hashtags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hashtag_path(@hashtag) %> |
<%= link_to 'Back', hashtags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SentimentAnalysis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentiment %>
    <%= f.text_area :sentiment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Sentiment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.sentiment %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sentiment:</strong>
  <%= @tweet.sentiment %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/twitter_users/_form.html.erb
<%= form_for(twitter_user) do |f| %>
  <% if twitter_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twitter_user.errors.count, "error") %> prohibited this twitter_user from being saved:</h2>

      <ul>
      <% twitter_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_area :username %>
  </div>

  <div class="field">
    <%= f.label :twittter_id %>
    <%= f.text_area :twittter_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_users/edit.html.erb
<h1>Editing Twitter User</h1>

<%= render 'form', twitter_user: @twitter_user %>

<%= link_to 'Show', @twitter_user %> |
<%= link_to 'Back', twitter_users_path %>

app/views/twitter_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twitter Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Twittter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twitter_users.each do |twitter_user| %>
      <tr>
        <td><%= twitter_user.username %></td>
        <td><%= twitter_user.twittter_id %></td>
        <td><%= link_to 'Show', twitter_user %></td>
        <td><%= link_to 'Edit', edit_twitter_user_path(twitter_user) %></td>
        <td><%= link_to 'Destroy', twitter_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twitter User', new_twitter_user_path %>

app/views/twitter_users/new.html.erb
<h1>New Twitter User</h1>

<%= render 'form', twitter_user: @twitter_user %>

<%= link_to 'Back', twitter_users_path %>

app/views/twitter_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @twitter_user.username %>
</p>

<p>
  <strong>Twittter:</strong>
  <%= @twitter_user.twittter_id %>
</p>

<%= link_to 'Edit', edit_twitter_user_path(@twitter_user) %> |
<%= link_to 'Back', twitter_users_path %>